### ISSUE TITLE
寻求帮助

### ISSUE THREAD

**Issue by w9595** [BIT-DA/JADA#1]
尊敬的作者您好：
       感谢您出色的工作，为域适应技术的发展做出了贡献。拜读了您的文献和代码，我有一点问题。我搞不清楚您文献中提到的领域对抗和类别对抗以及梯度反转时两个对抗的调节在代码中时如何体现出来的。请您不吝帮助我解答这个疑问。谢谢您。我的邮箱是2436934743@qq.com
      祝一切顺利！

**Comment by BinhuiXie** [comment]
Hi @w9595 

Thanks for your attention! 

First of all, due to one GRL between domain discriminator and feature generator and the other GRL between two classifiers and feature generator, we only need backward once during the training.

https://github.com/BIT-DA/JADA/blob/aed214358e4af7eb883464e0fed462683bac8bb0/Office31/train_office.py#L214-L217

Second, w.r.t. the implementation of two GRL, the following lines might be helpful!
1. GRL
https://github.com/BIT-DA/JADA/blob/aed214358e4af7eb883464e0fed462683bac8bb0/Office31/network.py#L8-L27

2. GRL applied between domain discriminator and feature generator
https://github.com/BIT-DA/JADA/blob/aed214358e4af7eb883464e0fed462683bac8bb0/Office31/network.py#L112

3. GRL applied between two classifiers and feature generator
https://github.com/BIT-DA/JADA/blob/aed214358e4af7eb883464e0fed462683bac8bb0/Office31/network.py#L178

**Comment by BinhuiXie** [comment]
I'm closing this issue. Pls feel free to ping me if there are further questions.

**Comment by w9595** [comment]
尊敬的作者您好：
       感谢您的回复与热心解答！我正在努力试图看懂您的论文和相应的代码。我的代码能力比较弱，还有些问题就是您的论文中提到的关于领域对抗和类别对抗的那些损失函数的公式，JADA的总体目标函数公式（8）,以及公式（9）-（12），这些公式在代码中是如何体现出来的？公式中有哪些参数是可以调节的？哪些参数是为模型的优化提供了贡献的？
       恳请您拨冗帮助我解答疑问。谢谢您。
       祝您万事顺利！
